"use client";
import Link from "next/link";
import { BasketForm } from "@/components/basket/BasketForm";
import { BasketResult } from "@/components/basket/BasketResult";
import { ErrorState, LoadingBlock } from "@/components/common/states";
import { Panel } from "@/components/common/ui";
import { ApiError, generateBasket, getUniverse } from "@/lib/api";
import { useAction, useRequest } from "@/lib/hooks";
import { describeError } from "@/lib/utils";
import { mapServerErrors } from "@/lib/validation";

export function QuickBasket() {
  const universe = useRequest(getUniverse, "universe");
  const { state, run } = useAction(generateBasket);
  const serverErrors = state.status === "error" && state.error instanceof ApiError ? mapServerErrors(state.error.details) : undefined;
  return (
    <Panel title="Quick basket" description="Generated by the backend from the full synthetic history.">
      <BasketForm onSubmit={run} loading={state.status === "loading"} maxSize={universe.data?.stocks.length} serverErrors={serverErrors} />
      <div className="mt-4">
        {state.status === "loading" && <LoadingBlock message="Generating basket..." />}
        {state.status === "error" && <ErrorState message={describeError(state.error, "the basket")} />}
        {state.status === "success" && (
          <>
            <BasketResult basket={state.data} universeSize={universe.data?.stocks.length} compact />
            <p className="mt-3 text-sm">
              <Link href="/basket" className="text-accent underline underline-offset-2">
                Open the full Basket Generator
              </Link>{" "}
              for reasons, charts and diagnostics.
            </p>
          </>
        )}
      </div>
    </Panel>
  );
}
